# permissions for end users to edit provisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: provision-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aviator
    app.kubernetes.io/part-of: aviator
    app.kubernetes.io/managed-by: kustomize
  name: provision-editor-role
rules:
- apiGroups:
  - vm.cloudclub.io
  resources:
  - provisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.cloudclub.io
  resources:
  - provisions/status
  verbs:
  - get
