apiVersion: v1
kind: Namespace
metadata:
  control-plane: controller-manager
  name: aviator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aviator
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        image: aviator-registry.kr.ncr.ntruss.com/aviator:latest
        imagePullPolicy: Always
        name: aviator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - name: config-volume
            mountPath: /etc/operator
      volumes:
        - name: config-volume
          configMap:
            name: aviator-config
