apiVersion: v1
kind: Service
metadata:
  name: aviator-controller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30000
  selector:
    control-plane: controller-manager

