namespace: aviator
namePrefix: aviator-
resources:
- aviator.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: aviator-registry.kr.ncr.ntruss.com/aviator
  newTag: 0376432e
patches:
- path: manager_auth_proxy_patch.yaml