namespace: aviator
namePrefix: aviator-
resources:
- aviator.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aviator
images:
- name: aviator-registry.kr.ncr.ntruss.com/aviator
  newTag: a26b3118100ce8378ca4b88bddb1822343dbfc97
resources:
- aviator.yaml
