namespace: aviator
namePrefix: aviator-
resources:
- aviator.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aviator
images:
- name: aviator-registry.kr.ncr.ntruss.com/aviator
  newTag: ce6163691cc2cdb977eb779e2e7b37d37ad28c05
resources:
- aviator.yaml
